import type { BallSpecs } from "../types/golf_ball";

// ゴルフボール物理スペックデータベース
// Gemini作成データベース（56モデル、2020-2026）
// D-Spin: ドライバースピン指数（低いほど曲がりにくい）
// W-Spin: ウェッジスピン指数（高いほど止まる）
// 弾道: 高さ指数（高いほど上がる）

export const BALL_DB: BallSpecs[] = [
    // === TITLEIST ===
    {
        id: "TL_PRO_V1_2025",
        brand: "Titleist",
        modelName: "Pro V1",
        releaseYear: 2025,
        structure: '3P',
        compression: 88,
        coverMaterial: 'URETHANE',
        dimpleCount: 388,
        dSpinIndex: 35,
        wSpinIndex: 95,
        trajectoryIndex: 45,
        priceYen: 7900,
        colorLineOptions: "W,Y / 矢印",
        recommendedHeadSpeed: { min: 40, max: 52 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'SIMPLE',
        usedByPros: ['S.シェフラー', 'V.ホブラン', '今平周吾', 'M.ホーマ', 'J.トーマス'],
        catchphrase: "世界中のプロが信頼するトータルパフォーマンス",
        description: "最高峰のスピン性能と飛距離のバランス。ツアーNo.1使用率。"
    },
    {
        id: "TL_PRO_V1X_2025",
        brand: "Titleist",
        modelName: "Pro V1x",
        releaseYear: 2025,
        structure: '4P',
        compression: 102,
        coverMaterial: 'URETHANE',
        dimpleCount: 348,
        dSpinIndex: 45,
        wSpinIndex: 98,
        trajectoryIndex: 75,
        priceYen: 7900,
        colorLineOptions: "W,Y / 矢印",
        recommendedHeadSpeed: { min: 45, max: 55 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'SIMPLE',
        usedByPros: ['L.アバーグ', 'P.カントレー', 'W.クラーク', 'N.コルダ', '蛭田みな美'],
        catchphrase: "高弾道とスピンコントロールの極み",
        description: "高Compでハードヒッター向け。高弾道で止まる。"
    },
    {
        id: "TL_LEFT_DASH_2024",
        brand: "Titleist",
        modelName: "Left Dash",
        releaseYear: 2024,
        structure: '4P',
        compression: 110,
        coverMaterial: 'URETHANE',
        dimpleCount: 328,
        dSpinIndex: 22,
        wSpinIndex: 85,
        trajectoryIndex: 80,
        priceYen: 7900,
        colorLineOptions: "W / シンプル",
        recommendedHeadSpeed: { min: 52, max: 60 },
        availableColors: ['ホワイト'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "ハードヒッター専用の低スピンモデル",
        description: "Comp 110。HS 52m/s以上のゴルファー専用。低スピンで飛ばす。"
    },
    {
        id: "TL_AVX_2024",
        brand: "Titleist",
        modelName: "AVX",
        releaseYear: 2024,
        structure: '3P',
        compression: 78,
        coverMaterial: 'URETHANE',
        dimpleCount: 348,
        dSpinIndex: 18,
        wSpinIndex: 80,
        trajectoryIndex: 25,
        priceYen: 7200,
        colorLineOptions: "W,Y / 長ライン",
        recommendedHeadSpeed: { min: 38, max: 48 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'SIMPLE',
        usedByPros: [],
        catchphrase: "低弾道・低スピンで風に負けない飛び",
        description: "Pro V1シリーズ最もソフト。スピン過多を抑えたい方に。"
    },
    {
        id: "TL_TOUR_SOFT_2026",
        brand: "Titleist",
        modelName: "Tour Soft",
        releaseYear: 2026,
        structure: '2P',
        compression: 74,
        coverMaterial: 'IONOMER',
        dimpleCount: 346,
        dSpinIndex: 25,
        wSpinIndex: 60,
        trajectoryIndex: 55,
        priceYen: 5500,
        colorLineOptions: "W,Y,G / T型",
        recommendedHeadSpeed: { min: 35, max: 45 },
        availableColors: ['ホワイト', 'イエロー', 'グリーン'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "ツアー品質をお手頃価格で",
        description: "アイオノマーカバーながらソフトな打感と操作性。"
    },
    {
        id: "TL_VELOCITY_2025",
        brand: "Titleist",
        modelName: "Velocity",
        releaseYear: 2025,
        structure: '2P',
        compression: 85,
        coverMaterial: 'IONOMER',
        dimpleCount: 350,
        dSpinIndex: 10,
        wSpinIndex: 32,
        trajectoryIndex: 70,
        priceYen: 3800,
        colorLineOptions: "4色 / マット",
        recommendedHeadSpeed: { min: 40, max: 50 },
        availableColors: ['ホワイト', 'イエロー', 'オレンジ', 'ピンク'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "距離を追求するディスタンス系",
        description: "とにかく飛距離を求める方に。D-Spin 10の超低スピン。"
    },
    {
        id: "TL_TRUFEEL_2024",
        brand: "Titleist",
        modelName: "TruFeel",
        releaseYear: 2024,
        structure: '2P',
        compression: 60,
        coverMaterial: 'IONOMER',
        dimpleCount: 376,
        dSpinIndex: 15,
        wSpinIndex: 40,
        trajectoryIndex: 35,
        priceYen: 3000,
        colorLineOptions: "W,Y,R / 太線",
        recommendedHeadSpeed: { min: 30, max: 38 },
        availableColors: ['ホワイト', 'イエロー', 'レッド'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "最もソフトなタイトリスト",
        description: "Comp 60。ヘッドスピード遅めの方でも潰して飛ばせる。"
    },

    // === BRIDGESTONE ===
    {
        id: "BS_TOUR_B_X_2026",
        brand: "Bridgestone",
        modelName: "TOUR B X",
        releaseYear: 2026,
        structure: '3P',
        compression: 98,
        coverMaterial: 'URETHANE',
        dimpleCount: 330,
        dSpinIndex: 20,
        wSpinIndex: 92,
        trajectoryIndex: 52,
        priceYen: 8200,
        colorLineOptions: "W,Y / サイト",
        recommendedHeadSpeed: { min: 45, max: 55 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'SIMPLE',
        usedByPros: ['T.ウッズ', 'J.デイ', '古江彩佳', '吉田優利', '比嘉一貴'],
        catchphrase: "タイガー・ウッズが選ぶ「乗り感」",
        description: "D-Spin 20の低スピン。飛んで止まる二刀流。"
    },
    {
        id: "BS_TOUR_B_XS_2026",
        brand: "Bridgestone",
        modelName: "TOUR B XS",
        releaseYear: 2026,
        structure: '3P',
        compression: 85,
        coverMaterial: 'URETHANE',
        dimpleCount: 330,
        dSpinIndex: 30,
        wSpinIndex: 100,
        trajectoryIndex: 48,
        priceYen: 8200,
        colorLineOptions: "W,Y / サイト",
        recommendedHeadSpeed: { min: 40, max: 50 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'SIMPLE',
        usedByPros: ['渡邉彩香', '佐久間朱莉', '堀琴音'],
        catchphrase: "W-Spin 100の最高スピン性能",
        description: "グリーンで「キュキュッ」と止まる。スピン重視派に。"
    },
    {
        id: "BS_TOUR_B_RX_2026",
        brand: "Bridgestone",
        modelName: "TOUR B RX",
        releaseYear: 2026,
        structure: '3P',
        compression: 82,
        coverMaterial: 'URETHANE',
        dimpleCount: 338,
        dSpinIndex: 18,
        wSpinIndex: 88,
        trajectoryIndex: 50,
        priceYen: 8200,
        colorLineOptions: "W,Y / サイト",
        recommendedHeadSpeed: { min: 38, max: 46 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "ソフトで飛ぶツアーボール",
        description: "RXシリーズの飛距離重視モデル。低スピンで直進性抜群。"
    },
    {
        id: "BS_TOUR_B_RXS_2026",
        brand: "Bridgestone",
        modelName: "TOUR B RXS",
        releaseYear: 2026,
        structure: '3P',
        compression: 78,
        coverMaterial: 'URETHANE',
        dimpleCount: 338,
        dSpinIndex: 25,
        wSpinIndex: 94,
        trajectoryIndex: 45,
        priceYen: 8200,
        colorLineOptions: "W,Y / サイト",
        recommendedHeadSpeed: { min: 35, max: 42 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "シニアにも最適なソフトスピン",
        description: "Comp 78でゆったりスイングでも飛ぶ。スピンも効く。"
    },
    {
        id: "BS_TOUR_B_JGR_2025",
        brand: "Bridgestone",
        modelName: "TOUR B JGR",
        releaseYear: 2025,
        structure: '3P',
        compression: 70,
        coverMaterial: 'IONOMER',
        dimpleCount: 338,
        dSpinIndex: 12,
        wSpinIndex: 38,
        trajectoryIndex: 85,
        priceYen: 6400,
        colorLineOptions: "4色 / 翼型",
        recommendedHeadSpeed: { min: 35, max: 45 },
        availableColors: ['ホワイト', 'イエロー', 'オレンジ', 'ピンク'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "弾道85の高弾道ディスタンス",
        description: "球が上がらない人に最適。高弾道で飛ばす。"
    },
    {
        id: "BS_SUPER_STRAIGHT_2025",
        brand: "Bridgestone",
        modelName: "Super Straight",
        releaseYear: 2025,
        structure: '3P',
        compression: 65,
        coverMaterial: 'IONOMER',
        dimpleCount: 326,
        dSpinIndex: 8,
        wSpinIndex: 28,
        trajectoryIndex: 60,
        priceYen: 3800,
        colorLineOptions: "3色 / 矢印",
        recommendedHeadSpeed: { min: 35, max: 42 },
        availableColors: ['ホワイト', 'イエロー', 'オレンジ'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "D-Spin 8の超直進性",
        description: "名前通りまっすぐ飛ぶ。スライサー必見。"
    },
    {
        id: "BS_EXTRA_SOFT_2025",
        brand: "Bridgestone",
        modelName: "Extra Soft",
        releaseYear: 2025,
        structure: '2P',
        compression: 62,
        coverMaterial: 'IONOMER',
        dimpleCount: 330,
        dSpinIndex: 14,
        wSpinIndex: 34,
        trajectoryIndex: 55,
        priceYen: 3200,
        colorLineOptions: "W,Y,O / 太線",
        recommendedHeadSpeed: { min: 30, max: 42 },
        availableColors: ['ホワイト', 'イエロー', 'オレンジ'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "ソフトな打感でやさしく飛ばす",
        description: "初心者、シニア、レディースに最適。"
    },
    {
        id: "BS_PHYZ_2024",
        brand: "Bridgestone",
        modelName: "PHYZ",
        releaseYear: 2024,
        structure: '4P',
        compression: 60,
        coverMaterial: 'IONOMER',
        dimpleCount: 338,
        dSpinIndex: 10,
        wSpinIndex: 35,
        trajectoryIndex: 90,
        priceYen: 9500,
        colorLineOptions: "3色 / パール",
        recommendedHeadSpeed: { min: 30, max: 38 },
        availableColors: ['ホワイト', 'パール', 'イエロー'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "弾道90の最高高弾道",
        description: "球が上がらない悩みを解決。プレミアムディスタンス。"
    },

    // === SRIXON ===
    {
        id: "SR_Z_STAR_2025",
        brand: "Srixon",
        modelName: "Z-STAR",
        releaseYear: 2025,
        structure: '3P',
        compression: 90,
        coverMaterial: 'URETHANE',
        dimpleCount: 338,
        dSpinIndex: 34,
        wSpinIndex: 98,
        trajectoryIndex: 42,
        priceYen: 7500,
        colorLineOptions: "W,Y / ナビ",
        recommendedHeadSpeed: { min: 40, max: 52 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'NAVI',
        usedByPros: ['山下美夢有', '岩井明愛', '香妻陣一朗', 'S.ローリー'],
        catchphrase: "W-Spin 98のプロが認めるスピン",
        description: "グリーン周りで威力を発揮するスピン特化。"
    },
    {
        id: "SR_Z_STAR_XV_2025",
        brand: "Srixon",
        modelName: "Z-STAR XV",
        releaseYear: 2025,
        structure: '3P',
        compression: 104,
        coverMaterial: 'URETHANE',
        dimpleCount: 338,
        dSpinIndex: 26,
        wSpinIndex: 93,
        trajectoryIndex: 72,
        priceYen: 7500,
        colorLineOptions: "W,Y / ナビ",
        recommendedHeadSpeed: { min: 48, max: 55 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'NAVI',
        usedByPros: ['松山英樹', '櫻井心那', '竹田麗央', '星野陸也', 'B.ケプカ'],
        catchphrase: "松山英樹の相棒、高弾道パワーボール",
        description: "Comp 104。ハードヒッターが高弾道で飛ばす。"
    },
    {
        id: "SR_Z_STAR_DIAMOND_2025",
        brand: "Srixon",
        modelName: "Z-STAR ◆",
        releaseYear: 2025,
        structure: '3P',
        compression: 98,
        coverMaterial: 'URETHANE',
        dimpleCount: 338,
        dSpinIndex: 42,
        wSpinIndex: 99,
        trajectoryIndex: 48,
        priceYen: 7500,
        colorLineOptions: "W / ナビ",
        recommendedHeadSpeed: { min: 45, max: 55 },
        availableColors: ['ホワイト'],
        hasAlignmentLine: true,
        alignmentLineType: 'NAVI',
        usedByPros: ['畑岡奈紗', '桂川有人', 'K.ブラッドリー', '小祝さくら'],
        catchphrase: "W-Spin 99の最高峰スピン",
        description: "ダイヤモンド。スピン性能を極めたツアーモデル。"
    },
    {
        id: "SR_DIVIDE_2025",
        brand: "Srixon",
        modelName: "Divide",
        releaseYear: 2025,
        structure: '3P',
        compression: 90,
        coverMaterial: 'URETHANE',
        dimpleCount: 338,
        dSpinIndex: 34,
        wSpinIndex: 98,
        trajectoryIndex: 42,
        priceYen: 7500,
        colorLineOptions: "2色 / ツートン",
        recommendedHeadSpeed: { min: 40, max: 50 },
        availableColors: ['イエロー/オレンジ', 'ブルー/イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "ツートンカラーで回転が見える",
        description: "Z-STARの視覚効果モデル。パッティングの回転確認に。"
    },
    {
        id: "SR_TRI_STAR_2024",
        brand: "Srixon",
        modelName: "TRI-STAR",
        releaseYear: 2024,
        structure: '3P',
        compression: 80,
        coverMaterial: 'IONOMER',
        dimpleCount: 338,
        dSpinIndex: 25,
        wSpinIndex: 65,
        trajectoryIndex: 58,
        priceYen: 4200,
        colorLineOptions: "W,Y / ナビ",
        recommendedHeadSpeed: { min: 40, max: 48 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "トータルバランスのミッドレンジ",
        description: "飛距離とスピンのバランスが良いコスパモデル。"
    },
    {
        id: "SR_AD_SPEED_2026",
        brand: "Srixon",
        modelName: "AD Speed",
        releaseYear: 2026,
        structure: '2P',
        compression: 76,
        coverMaterial: 'IONOMER',
        dimpleCount: 338,
        dSpinIndex: 18,
        wSpinIndex: 35,
        trajectoryIndex: 62,
        priceYen: 2800,
        colorLineOptions: "W,Y / 矢印",
        recommendedHeadSpeed: { min: 35, max: 48 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "コスパ抜群のディスタンス系",
        description: "お手頃価格で飛距離を追求。練習にも最適。"
    },
    {
        id: "SR_SOFT_FEEL_2025",
        brand: "Srixon",
        modelName: "Soft Feel",
        releaseYear: 2025,
        structure: '2P',
        compression: 60,
        coverMaterial: 'IONOMER',
        dimpleCount: 338,
        dSpinIndex: 16,
        wSpinIndex: 32,
        trajectoryIndex: 68,
        priceYen: 2500,
        colorLineOptions: "3色 / 柔文字",
        recommendedHeadSpeed: { min: 30, max: 42 },
        availableColors: ['ホワイト', 'イエロー', 'オレンジ'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "名前通りのソフトな打感",
        description: "Comp 60。やさしく飛ばせるエントリーモデル。"
    },
    {
        id: "SR_DISTANCE_2022",
        brand: "Srixon",
        modelName: "Distance",
        releaseYear: 2022,
        structure: '2P',
        compression: 85,
        coverMaterial: 'IONOMER',
        dimpleCount: 324,
        dSpinIndex: 12,
        wSpinIndex: 22,
        trajectoryIndex: 65,
        priceYen: 2100,
        colorLineOptions: "W,Y / シンプル",
        recommendedHeadSpeed: { min: 35, max: 48 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "最低価格で飛ばす",
        description: "とにかく安く飛距離を。練習用にも最適。"
    },

    // === TAYLORMADE ===
    {
        id: "TM_TP5_2026",
        brand: "TaylorMade",
        modelName: "TP5",
        releaseYear: 2026,
        structure: '5P',
        compression: 83,
        coverMaterial: 'URETHANE',
        dimpleCount: 322,
        dSpinIndex: 32,
        wSpinIndex: 96,
        trajectoryIndex: 45,
        priceYen: 8500,
        colorLineOptions: "W,Y / pix",
        recommendedHeadSpeed: { min: 40, max: 52 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'PIX',
        usedByPros: ['T.フリートウッド', '中島啓太', '渋野日向子', 'B.ヘンダーソン'],
        catchphrase: "5ピース構造の打感とスピン",
        description: "唯一の5層構造。番手ごとに最適なスピン。"
    },
    {
        id: "TM_TP5X_2026",
        brand: "TaylorMade",
        modelName: "TP5x",
        releaseYear: 2026,
        structure: '5P',
        compression: 100,
        coverMaterial: 'URETHANE',
        dimpleCount: 322,
        dSpinIndex: 18,
        wSpinIndex: 88,
        trajectoryIndex: 70,
        priceYen: 8500,
        colorLineOptions: "W,Y / pix",
        recommendedHeadSpeed: { min: 48, max: 55 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'PIX',
        usedByPros: ['R.マキロイ', 'C.モリカワ', 'D.ジョンソン', '久常涼', 'N.テイラー'],
        catchphrase: "世界ランカーが選ぶ高弾道パワーボール",
        description: "D-Spin 18の低スピンで飛ばし、高弾道で止める。"
    },
    {
        id: "TM_TP5_STRIPE_2026",
        brand: "TaylorMade",
        modelName: "TP5 Stripe",
        releaseYear: 2026,
        structure: '5P',
        compression: 83,
        coverMaterial: 'URETHANE',
        dimpleCount: 322,
        dSpinIndex: 32,
        wSpinIndex: 96,
        trajectoryIndex: 45,
        priceYen: 8900,
        colorLineOptions: "Stripe / 360°",
        recommendedHeadSpeed: { min: 40, max: 52 },
        availableColors: ['レッドストライプ', 'イエローストライプ'],
        hasAlignmentLine: true,
        alignmentLineType: 'STRIPE',
        usedByPros: [],
        catchphrase: "360°ストライプで回転が見える",
        description: "TP5の視覚効果モデル。パッティング改善に。"
    },
    {
        id: "TM_TOUR_RESPONSE_2025",
        brand: "TaylorMade",
        modelName: "Tour Response",
        releaseYear: 2025,
        structure: '3P',
        compression: 74,
        coverMaterial: 'URETHANE',
        dimpleCount: 322,
        dSpinIndex: 22,
        wSpinIndex: 86,
        trajectoryIndex: 55,
        priceYen: 5800,
        colorLineOptions: "W,Y,S / Stripe",
        recommendedHeadSpeed: { min: 38, max: 48 },
        availableColors: ['ホワイト', 'イエロー', 'ストライプ'],
        hasAlignmentLine: true,
        alignmentLineType: 'STRIPE',
        usedByPros: [],
        catchphrase: "ツアー品質をお手頃価格で",
        description: "ウレタンカバーながらコスパ抜群のツアーボール。"
    },
    {
        id: "TM_SPEEDSOFT_2025",
        brand: "TaylorMade",
        modelName: "Speedsoft",
        releaseYear: 2025,
        structure: '2P',
        compression: 60,
        coverMaterial: 'IONOMER',
        dimpleCount: 332,
        dSpinIndex: 15,
        wSpinIndex: 42,
        trajectoryIndex: 70,
        priceYen: 3800,
        colorLineOptions: "Ink / ペイント",
        recommendedHeadSpeed: { min: 30, max: 42 },
        availableColors: ['ホワイト', 'イエロー', 'インクデザイン'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "ソフトで高弾道のディスタンス",
        description: "Comp 60。ゆったりスイングで高く飛ばす。"
    },
    {
        id: "TM_DISTANCE_SOFT_2024",
        brand: "TaylorMade",
        modelName: "Distance+ Soft",
        releaseYear: 2024,
        structure: '2P',
        compression: 70,
        coverMaterial: 'IONOMER',
        dimpleCount: 342,
        dSpinIndex: 10,
        wSpinIndex: 25,
        trajectoryIndex: 65,
        priceYen: 2400,
        colorLineOptions: "W,Y / 十字",
        recommendedHeadSpeed: { min: 35, max: 45 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "D-Spin 10の超直進性",
        description: "とにかく曲がらない。飛距離重視の方に。"
    },

    // === CALLAWAY ===
    {
        id: "CW_CHROME_TOUR_2025",
        brand: "Callaway",
        modelName: "Chrome Tour",
        releaseYear: 2025,
        structure: '4P',
        compression: 96,
        coverMaterial: 'URETHANE',
        dimpleCount: 332,
        dSpinIndex: 24,
        wSpinIndex: 95,
        trajectoryIndex: 55,
        priceYen: 8000,
        colorLineOptions: "W,Y / 3本線",
        recommendedHeadSpeed: { min: 45, max: 55 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'TRIPLE_TRACK',
        usedByPros: ['X.シャウフェレ', '石川遼', '西村優菜', '河本結', 'M.リー'],
        catchphrase: "トリプルトラックで正確なパッティング",
        description: "4ピース構造でツアー品質。視覚効果も抜群。"
    },
    {
        id: "CW_CHROME_TOUR_X_2025",
        brand: "Callaway",
        modelName: "Chrome Tour X",
        releaseYear: 2025,
        structure: '4P',
        compression: 102,
        coverMaterial: 'URETHANE',
        dimpleCount: 332,
        dSpinIndex: 34,
        wSpinIndex: 99,
        trajectoryIndex: 75,
        priceYen: 8000,
        colorLineOptions: "W,Y / 3本線",
        recommendedHeadSpeed: { min: 48, max: 55 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'TRIPLE_TRACK',
        usedByPros: ['J.ラーム', '笹生優花', 'A.バティア', 'S.バーンズ', '上田桃子'],
        catchphrase: "W-Spin 99のハイスピンツアーボール",
        description: "Comp 102。ハードヒッターがスピンで止める。"
    },
    {
        id: "CW_CHROME_SOFT_2025",
        brand: "Callaway",
        modelName: "Chrome Soft",
        releaseYear: 2025,
        structure: '3P',
        compression: 75,
        coverMaterial: 'URETHANE',
        dimpleCount: 332,
        dSpinIndex: 20,
        wSpinIndex: 90,
        trajectoryIndex: 60,
        priceYen: 8000,
        colorLineOptions: "W,Y / 3本線",
        recommendedHeadSpeed: { min: 40, max: 48 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        alignmentLineType: 'TRIPLE_TRACK',
        usedByPros: [],
        catchphrase: "ソフトなのに止まるツアーボール",
        description: "Comp 75。ソフトな打感でスピンも効く。"
    },
    {
        id: "CW_ERC_SOFT_2025",
        brand: "Callaway",
        modelName: "ERC Soft",
        releaseYear: 2025,
        structure: '3P',
        compression: 65,
        coverMaterial: 'HYBRID',
        dimpleCount: 332,
        dSpinIndex: 15,
        wSpinIndex: 58,
        trajectoryIndex: 82,
        priceYen: 6200,
        colorLineOptions: "W,Y / フェード",
        recommendedHeadSpeed: { min: 35, max: 45 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "高弾道82で球が上がる",
        description: "球が上がらない悩みを解決。ハイブリッドカバー。"
    },
    {
        id: "CW_SUPERSOFT_2025",
        brand: "Callaway",
        modelName: "Supersoft",
        releaseYear: 2025,
        structure: '2P',
        compression: 55,
        coverMaterial: 'IONOMER',
        dimpleCount: 332,
        dSpinIndex: 12,
        wSpinIndex: 35,
        trajectoryIndex: 78,
        priceYen: 3500,
        colorLineOptions: "4色 / マット",
        recommendedHeadSpeed: { min: 30, max: 40 },
        availableColors: ['ホワイト', 'イエロー', 'オレンジ', 'ピンク'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "Comp 55の超ソフト",
        description: "最もソフトなキャロウェイ。誰でも飛ばせる。"
    },
    {
        id: "CW_WARBIRD_2025",
        brand: "Callaway",
        modelName: "Warbird",
        releaseYear: 2025,
        structure: '2P',
        compression: 85,
        coverMaterial: 'IONOMER',
        dimpleCount: 332,
        dSpinIndex: 18,
        wSpinIndex: 25,
        trajectoryIndex: 62,
        priceYen: 2600,
        colorLineOptions: "W,Y / シンプル",
        recommendedHeadSpeed: { min: 40, max: 50 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "コスパ抜群の飛距離ボール",
        description: "お手頃価格で飛距離を追求。"
    },
    {
        id: "CW_REVA_2025",
        brand: "Callaway",
        modelName: "Reva",
        releaseYear: 2025,
        structure: '2P',
        compression: 50,
        coverMaterial: 'IONOMER',
        dimpleCount: 332,
        dSpinIndex: 14,
        wSpinIndex: 30,
        trajectoryIndex: 85,
        priceYen: 4200,
        colorLineOptions: "W,P / パール",
        recommendedHeadSpeed: { min: 25, max: 35 },
        availableColors: ['ホワイト', 'ピンク', 'パール'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "レディース専用設計",
        description: "Comp 50。ゆったりスイングでも高く飛ぶ。"
    },

    // === MIZUNO ===
    {
        id: "MZ_RB_TOUR_2024",
        brand: "Mizuno",
        modelName: "RB TOUR",
        releaseYear: 2024,
        structure: '3P',
        compression: 92,
        coverMaterial: 'URETHANE',
        dimpleCount: 360,
        dSpinIndex: 34,
        wSpinIndex: 92,
        trajectoryIndex: 48,
        priceYen: 6800,
        colorLineOptions: "W / C-Dim",
        recommendedHeadSpeed: { min: 40, max: 52 },
        availableColors: ['ホワイト'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "ミズノのツアークオリティ",
        description: "360個のC-Dimディンプルで安定した弾道。"
    },
    {
        id: "MZ_RB_TOUR_X_2024",
        brand: "Mizuno",
        modelName: "RB TOUR X",
        releaseYear: 2024,
        structure: '3P',
        compression: 102,
        coverMaterial: 'URETHANE',
        dimpleCount: 360,
        dSpinIndex: 40,
        wSpinIndex: 94,
        trajectoryIndex: 70,
        priceYen: 6800,
        colorLineOptions: "W / C-Dim",
        recommendedHeadSpeed: { min: 48, max: 55 },
        availableColors: ['ホワイト'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "ハードヒッター向け高弾道",
        description: "Comp 102で速いスイングを活かす。"
    },
    {
        id: "MZ_RB_MAX_2025",
        brand: "Mizuno",
        modelName: "RB MAX",
        releaseYear: 2025,
        structure: '3P',
        compression: 82,
        coverMaterial: 'IONOMER',
        dimpleCount: 336,
        dSpinIndex: 22,
        wSpinIndex: 65,
        trajectoryIndex: 65,
        priceYen: 4500,
        colorLineOptions: "W,Y / 縦線",
        recommendedHeadSpeed: { min: 40, max: 48 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "飛距離とスピンのバランス",
        description: "ミッドレンジのオールラウンダー。"
    },
    {
        id: "MZ_RB_566V_2023",
        brand: "Mizuno",
        modelName: "RB 566V",
        releaseYear: 2023,
        structure: '3P',
        compression: 78,
        coverMaterial: 'IONOMER',
        dimpleCount: 566,
        dSpinIndex: 18,
        wSpinIndex: 40,
        trajectoryIndex: 75,
        priceYen: 3500,
        colorLineOptions: "W,Y / D-Dim",
        recommendedHeadSpeed: { min: 38, max: 45 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "566個のディンプルで高弾道",
        description: "業界最多のディンプル数で揚力を最大化。"
    },

    // === HONMA ===
    {
        id: "HM_TW_X_2026",
        brand: "Honma",
        modelName: "TW-X",
        releaseYear: 2026,
        structure: '3P',
        compression: 95,
        coverMaterial: 'URETHANE',
        dimpleCount: 326,
        dSpinIndex: 28,
        wSpinIndex: 91,
        trajectoryIndex: 52,
        priceYen: 5500,
        colorLineOptions: "W,Y / シンプル",
        recommendedHeadSpeed: { min: 45, max: 55 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "本間のツアー品質",
        description: "飛距離とスピンのバランスが良いツアーモデル。"
    },
    {
        id: "HM_TW_S_2026",
        brand: "Honma",
        modelName: "TW-S",
        releaseYear: 2026,
        structure: '3P',
        compression: 82,
        coverMaterial: 'URETHANE',
        dimpleCount: 326,
        dSpinIndex: 26,
        wSpinIndex: 94,
        trajectoryIndex: 48,
        priceYen: 5500,
        colorLineOptions: "W,Y / シンプル",
        recommendedHeadSpeed: { min: 40, max: 48 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "ソフトでスピンが効く",
        description: "TWシリーズのスピン重視モデル。"
    },
    {
        id: "HM_D1_2026",
        brand: "Honma",
        modelName: "D1",
        releaseYear: 2026,
        structure: '2P',
        compression: 82,
        coverMaterial: 'IONOMER',
        dimpleCount: 368,
        dSpinIndex: 10,
        wSpinIndex: 25,
        trajectoryIndex: 78,
        priceYen: 2300,
        colorLineOptions: "5色 / 強調",
        recommendedHeadSpeed: { min: 35, max: 48 },
        availableColors: ['ホワイト', 'イエロー', 'オレンジ', 'ピンク', 'グリーン'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "D-Spin 10の超直進性",
        description: "低価格で驚異の直進性。カラーも豊富。"
    },
    {
        id: "HM_D1_SPEED_2024",
        brand: "Honma",
        modelName: "D1 Speed Monster",
        releaseYear: 2024,
        structure: '3P',
        compression: 88,
        coverMaterial: 'IONOMER',
        dimpleCount: 368,
        dSpinIndex: 15,
        wSpinIndex: 30,
        trajectoryIndex: 80,
        priceYen: 3500,
        colorLineOptions: "W,Y / 黄ロゴ",
        recommendedHeadSpeed: { min: 40, max: 50 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "D1の飛距離をさらに強化",
        description: "高弾道80で飛ばす進化版D1。"
    },

    // === KASCO ===
    {
        id: "KC_DNA_2025",
        brand: "Kasco",
        modelName: "DNA",
        releaseYear: 2025,
        structure: '3P',
        compression: 68,
        coverMaterial: 'IONOMER',
        dimpleCount: 362,
        dSpinIndex: 18,
        wSpinIndex: 42,
        trajectoryIndex: 80,
        priceYen: 4800,
        colorLineOptions: "W,Y / 反射",
        recommendedHeadSpeed: { min: 35, max: 43 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "高弾道で飛ばすディスタンス",
        description: "球が上がらない悩みを解決。"
    },
    {
        id: "KC_KIRA_DIAMOND_2024",
        brand: "Kasco",
        modelName: "Kira Diamond",
        releaseYear: 2024,
        structure: '3P',
        compression: 75,
        coverMaterial: 'IONOMER',
        dimpleCount: 362,
        dSpinIndex: 22,
        wSpinIndex: 55,
        trajectoryIndex: 82,
        priceYen: 8500,
        colorLineOptions: "多色 / 蛍光",
        recommendedHeadSpeed: { min: 35, max: 45 },
        availableColors: ['パール', 'ピンク', 'イエロー', 'オレンジ', 'アクア'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "華やかな蛍光カラーで視認性抜群",
        description: "プレミアムディスタンスの蛍光モデル。"
    },
    {
        id: "KC_ZEUS_IMPACT_2026",
        brand: "Kasco",
        modelName: "Zeus Impact 3",
        releaseYear: 2026,
        structure: '3P',
        compression: 80,
        coverMaterial: 'IONOMER',
        dimpleCount: 362,
        dSpinIndex: 5,
        wSpinIndex: 20,
        trajectoryIndex: 90,
        priceYen: 8000,
        colorLineOptions: "W,Y / 非公認",
        recommendedHeadSpeed: { min: 35, max: 42 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "D-Spin 5の超低スピン（高反発）",
        description: "非公認ボール。とにかく飛ばしたい方に。"
    },

    // === VOLVIK ===
    {
        id: "VK_CONDOR_2024",
        brand: "Volvik",
        modelName: "Condor",
        releaseYear: 2024,
        structure: '3P',
        compression: 90,
        coverMaterial: 'URETHANE',
        dimpleCount: 336,
        dSpinIndex: 32,
        wSpinIndex: 92,
        trajectoryIndex: 55,
        priceYen: 7200,
        colorLineOptions: "W / サイト",
        recommendedHeadSpeed: { min: 42, max: 55 },
        availableColors: ['ホワイト'],
        hasAlignmentLine: true,
        usedByPros: ['B.ワトソン'],
        catchphrase: "バッバ・ワトソンの相棒",
        description: "ツアー品質のスピン性能。"
    },
    {
        id: "VK_VIVID_2025",
        brand: "Volvik",
        modelName: "VIVID",
        releaseYear: 2025,
        structure: '3P',
        compression: 85,
        coverMaterial: 'IONOMER',
        dimpleCount: 322,
        dSpinIndex: 40,
        wSpinIndex: 50,
        trajectoryIndex: 72,
        priceYen: 5200,
        colorLineOptions: "8色 / マット",
        recommendedHeadSpeed: { min: 38, max: 48 },
        availableColors: ['レッド', 'オレンジ', 'イエロー', 'グリーン', 'ブルー', 'ピンク', 'パープル', 'ホワイト'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "8色のマットカラーで目立つ",
        description: "視認性抜群。ファッショナブルなゴルフを。"
    },
    {
        id: "VK_S4_2024",
        brand: "Volvik",
        modelName: "S4",
        releaseYear: 2024,
        structure: '4P',
        compression: 105,
        coverMaterial: 'URETHANE',
        dimpleCount: 336,
        dSpinIndex: 35,
        wSpinIndex: 95,
        trajectoryIndex: 52,
        priceYen: 7200,
        colorLineOptions: "W,G / ロゴ",
        recommendedHeadSpeed: { min: 48, max: 55 },
        availableColors: ['ホワイト', 'グリーン'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "Comp 105のハードヒッター向け",
        description: "4ピース構造で高いスピン性能。"
    },

    // === VICE ===
    {
        id: "VC_PRO_PLUS_2024",
        brand: "Vice",
        modelName: "Pro Plus",
        releaseYear: 2024,
        structure: '4P',
        compression: 95,
        coverMaterial: 'URETHANE',
        dimpleCount: 336,
        dSpinIndex: 38,
        wSpinIndex: 92,
        trajectoryIndex: 68,
        priceYen: 5800,
        colorLineOptions: "3色 / ドリップ",
        recommendedHeadSpeed: { min: 45, max: 55 },
        availableColors: ['ホワイト', 'レッド', 'ネオン'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "コスパ抜群のD2Cツアーボール",
        description: "直販でプレミアム品質をお手頃価格で。"
    },
    {
        id: "VC_PRO_AIR_2025",
        brand: "Vice",
        modelName: "Pro Air",
        releaseYear: 2025,
        structure: '3P',
        compression: 78,
        coverMaterial: 'URETHANE',
        dimpleCount: 318,
        dSpinIndex: 24,
        wSpinIndex: 82,
        trajectoryIndex: 55,
        priceYen: 5800,
        colorLineOptions: "W,Y / シンプル",
        recommendedHeadSpeed: { min: 40, max: 50 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "ソフトなツアーボールをお手頃で",
        description: "ウレタンカバーでスピン性能も確保。"
    },

    // === SNELL ===
    {
        id: "SN_MTB_PRIME_2024",
        brand: "Snell",
        modelName: "MTB Prime",
        releaseYear: 2024,
        structure: '3P',
        compression: 92,
        coverMaterial: 'URETHANE',
        dimpleCount: 360,
        dSpinIndex: 30,
        wSpinIndex: 94,
        trajectoryIndex: 52,
        priceYen: 5500,
        colorLineOptions: "W,Y / シンプル",
        recommendedHeadSpeed: { min: 42, max: 55 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "元タイトリスト設計者のD2Cボール",
        description: "ディーン・スネル設計のツアークオリティ。"
    },

    // === XXIO ===
    {
        id: "XX_REBOUND_2024",
        brand: "XXIO",
        modelName: "Rebound Drive",
        releaseYear: 2024,
        structure: '3P',
        compression: 78,
        coverMaterial: 'HYBRID',
        dimpleCount: 338,
        dSpinIndex: 20,
        wSpinIndex: 70,
        trajectoryIndex: 65,
        priceYen: 6800,
        colorLineOptions: "4色 / Xマーク",
        recommendedHeadSpeed: { min: 35, max: 45 },
        availableColors: ['ホワイト', 'イエロー', 'ピンク', 'プレミアムホワイト'],
        hasAlignmentLine: true,
        usedByPros: [],
        catchphrase: "ゼクシオブランドの安心感",
        description: "ゆったりスイングで飛ばす。シニア・レディースに。"
    },

    // === KIRKLAND ===
    {
        id: "KL_PERFORMANCE_3_2024",
        brand: "Kirkland",
        modelName: "Performance+ 3",
        releaseYear: 2024,
        structure: '3P',
        compression: 90,
        coverMaterial: 'URETHANE',
        dimpleCount: 338,
        dSpinIndex: 55,
        wSpinIndex: 95,
        trajectoryIndex: 62,
        priceYen: 3800,
        colorLineOptions: "W,Y / シンプル",
        recommendedHeadSpeed: { min: 40, max: 52 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: false,
        usedByPros: [],
        catchphrase: "コストコの驚異的コスパ",
        description: "ウレタンカバーで¥3,800。練習には最適解。"
    },

    // === WILSON ===
    {
        id: "WL_STAFF_MODEL_2024",
        brand: "Wilson",
        modelName: "Staff Model",
        releaseYear: 2024,
        structure: '4P',
        compression: 100,
        coverMaterial: 'URETHANE',
        dimpleCount: 362,
        dSpinIndex: 35,
        wSpinIndex: 94,
        trajectoryIndex: 55,
        priceYen: 7500,
        colorLineOptions: "W,Y / シンプル",
        recommendedHeadSpeed: { min: 48, max: 55 },
        availableColors: ['ホワイト', 'イエロー'],
        hasAlignmentLine: false,
        usedByPros: ['P.ハリントン'],
        catchphrase: "パドレイグ・ハリントンの相棒",
        description: "老舗ウィルソンのツアーモデル。"
    }
];

// ヘルパー関数: 物理適合スコア計算
export const calcPhysicsScore = (headSpeed: number, compression: number): number => {
    return 100 - Math.abs((headSpeed * 2.1) - compression);
};

// ヘルパー関数: D-Spinからスピン傾向を導出
export const getDSpinTendency = (dSpinIndex: number): 'LOW' | 'MID' | 'HIGH' => {
    if (dSpinIndex <= 20) return 'LOW';
    if (dSpinIndex <= 35) return 'MID';
    return 'HIGH';
};

// ヘルパー関数: W-Spinからウェッジスピン傾向を導出
export const getWSpinTendency = (wSpinIndex: number): 'LOW' | 'MID' | 'HIGH' => {
    if (wSpinIndex <= 50) return 'LOW';
    if (wSpinIndex <= 85) return 'MID';
    return 'HIGH';
};

// ヘルパー関数: 弾道指数から弾道傾向を導出
export const getTrajectoryTendency = (trajectoryIndex: number): 'LOW' | 'MID' | 'HIGH' => {
    if (trajectoryIndex <= 45) return 'LOW';
    if (trajectoryIndex <= 65) return 'MID';
    return 'HIGH';
};
