export interface ProfileSocialOverride {
  instagramHandle?: string;
  xHandle?: string;
}

export const profileSocialOverrides: Record<string, ProfileSocialOverride> = {
  'adam-scott': { instagramHandle: 'adamscottofficial' },
  'aguri-iwasaki': { instagramHandle: 'aguri_iwasaki' },
  'ai-suzuki': { instagramHandle: 'ai_suzuki59' },
  'akie-iwai': { instagramHandle: 'akie.iwai' },
  'allisen-corpuz': { instagramHandle: 'allisencorpuz', xHandle: 'allisencorpuz' },
  'ally-ewing': { instagramHandle: 'allymc10', xHandle: 'allyewing' },
  'amiyu-ozeki': { instagramHandle: 'amiyu_ozeki' },
  'amy-yang': { instagramHandle: 'amy_yang_golf' },
  'andrea-lee': { instagramHandle: 'andrea_lee54', xHandle: 'andrea_lee54' },
  'angel-yin': { instagramHandle: 'angelyinlol', xHandle: 'angelyinlol' },
  'anna-nordqvist': { instagramHandle: 'a_nordqvist', xHandle: 'ANordqvist' },
  'aoki-serena': { instagramHandle: 'serenaaoki_official' },
  'arimura-chie': { instagramHandle: 'chiearimura' },
  'ariya-jutanugarn': { instagramHandle: 'mayariya' },
  'ashleigh-buhai': { instagramHandle: 'ashbuhaigolf', xHandle: 'ashbuhai' },
  'asuka-kashiwabara': { instagramHandle: 'asuka_kashiwabara_official' },
  'ayaka-watanabe': { instagramHandle: 'ayaka_watanabe_official' },
  'ayaka-furue': { instagramHandle: 'ayaka_furue27' },
  'ayako-kimura': { instagramHandle: 'ayako_kimura_official' },
  'ayano-yasuda': { instagramHandle: 'ayano_yasuda_official' },
  'brian-harman': { instagramHandle: 'harmanbrian' },
  'brooke-henderson': { instagramHandle: 'brookehendersongolf' },
  'brooks-koepka': { instagramHandle: 'bkoepka', xHandle: 'BKoepka' },
  'chisato-iwai': { instagramHandle: 'chisato.iwai' },
  'collin-morikawa': { instagramHandle: 'collin_morikawa' },
  'charley-hull': { instagramHandle: 'charley.hull' },
  'cameron-smith': { instagramHandle: 'camsmithgolf' },
  'cameron-young': { instagramHandle: 'cameron_young' },
  'carlota-ciganda': { instagramHandle: 'carlotaciganda', xHandle: 'carlotagolf' },
  'celine-boutier': { instagramHandle: 'celineboutier', xHandle: 'celineboutier' },
  'corey-conners': { instagramHandle: 'coreyconners', xHandle: 'coreconn' },
  'daijiro-izumida': { instagramHandle: 'daijiro.izumida' },
  'danielle-kang': { instagramHandle: 'daniellekang', xHandle: 'daniellekang' },
  'eri-okayama': { instagramHandle: 'eri_okayama_official' },
  'erika-hara': { instagramHandle: 'erika_hara_official' },
  'erika-kikuchi': { instagramHandle: 'erika_kikuchi_official' },
  'fukuda-mami': { instagramHandle: 'fukudamami32' },
  'gaby-lopez': { instagramHandle: 'gabylopezgolf', xHandle: 'GabyLopezGOLF' },
  'georgia-hall': { instagramHandle: 'georgiahall23', xHandle: 'georgiahall96' },
  'goto-miu': { instagramHandle: 'miu_goto_official' },
  'haeran-ryu': { instagramHandle: 'haeran_ryu' },
  'hannah-green': { instagramHandle: 'hannahgreengolf', xHandle: 'hannahgreengolf' },
  'haruka-amamoto': { instagramHandle: 'haruka_amamoto' },
  'haruka-kawasaki': { instagramHandle: 'haru_1582' },
  'hibiki-iriya': { instagramHandle: 'hibiki_iriya' },
  'jason-day': { instagramHandle: 'jdaygolf' },
  'jeeno-thitikul': { instagramHandle: 'jeenothitikul' },
  'jennifer-kupcho': { instagramHandle: 'jenniferkupcho', xHandle: 'jenniferkupcho' },
  'jin-young-ko': { instagramHandle: 'jinyoungko_official' },
  'jinichiro-kozuma': { instagramHandle: 'jinichiro_kozuma' },
  'inbee-park': { instagramHandle: 'inbeepark' },
  'joaquin-niemann': { instagramHandle: 'joaco_niemann' },
  'jon-rahm': { instagramHandle: 'jonrahm' },
  'jordan-spieth': { instagramHandle: 'jordanspieth' },
  'justin-thomas': { instagramHandle: 'justinthomas34' },
  'hideki-matsuyama': { instagramHandle: 'hideki.matsuyama_official' },
  'hideto-tanihara': { instagramHandle: 'hideto_tanihara' },
  'hinako-shibuno': { instagramHandle: 'pinacoooon' },
  'in-gee-chun': { instagramHandle: 'ingeechun_dumbo' },
  'justin-rose': { instagramHandle: 'justinprose99' },
  'kanako-aoki': { instagramHandle: 'knk_aoki' },
  'kanazawa-shina': { instagramHandle: 'shina_kanazawa' },
  'kaito-onishi': { instagramHandle: 'kaito_onishi' },
  'karen-fujita': { instagramHandle: 'fujitakaren_official' },
  'kasa-ritsuko': { instagramHandle: 'ritsukokasa_official' },
  'katsumasa-miyamoto': { instagramHandle: 'katsumasa_miyamoto' },
  'kawagishi-fumika': { instagramHandle: 'fumikakawagishi' },
  'kazuki-higa': { instagramHandle: 'kazukihiga_official' },
  'keegan-bradley': { instagramHandle: 'keeganbradley1' },
  'keita-nakajima': { instagramHandle: 'keita.n_0624' },
  'kensei-hirata': { instagramHandle: 'k_e_n_s_e_i_1126' },
  'kido-ai': { instagramHandle: 'megumikido_official' },
  'kokona-sakurai': { instagramHandle: 'kokona_sakurai' },
  'kokone-yoshimoto': { instagramHandle: 'kokone_yoshimoto' },
  'konosuke-nakazato': { instagramHandle: 'konosuke_nakazato' },
  'kotaki-mion': { instagramHandle: 'mion_kotaki' },
  'kotoko-uchida': { instagramHandle: 'kotoko_uchida' },
  'kozuma-kotono': { instagramHandle: 'kotono_kozuma_official' },
  'kotone-hori': { instagramHandle: 'kotone_hori_official' },
  'kumiko-kaneda': { instagramHandle: 'kinkumikumi' },
  'lauren-coughlin': { instagramHandle: 'lauren.coughlin' },
  'leona-maguire': { instagramHandle: 'leona_maguire', xHandle: 'leona_maguire' },
  'lexi-thompson': { instagramHandle: 'lexi' },
  'lilia-vu': { instagramHandle: 'liliavu' },
  'linn-grant': { instagramHandle: 'linngrant' },
  'ludvig-aberg': { instagramHandle: 'ludvig_aberg' },
  'lydia-ko': { instagramHandle: 'lydsko' },
  'mamiko-higa': { instagramHandle: 'mamiko_higa_official' },
  'mao-saigo': { instagramHandle: 'mao_saigo_official' },
  'maya-stark': { instagramHandle: 'mayastark' },
  'megan-khang': { instagramHandle: 'megankhang1023', xHandle: 'megankhang1023' },
  'mikiya-akutsu': { instagramHandle: 'mikiya_akutsu' },
  'mikumu-horikawa': { instagramHandle: 'mikumu.h' },
  'minami-katsu': { instagramHandle: 'minami_katsu' },
  'matt-fitzpatrick': { instagramHandle: 'mattfitz94' },
  'matt-mccarty': { instagramHandle: 'mattmccarty21', xHandle: 'mattmccarty21' },
  'max-homa': { instagramHandle: 'max.homa', xHandle: 'maxhoma23' },
  'min-woo-lee': { instagramHandle: 'minwoo27lee' },
  'minjee-lee': { instagramHandle: 'minjee27' },
  'mone-inami': { instagramHandle: 'moneinami_official' },
  'morita-haruka': { instagramHandle: 'haruka.morita_official' },
  'morita-rikako': { instagramHandle: 'rikakomorita_official' },
  'moriya-jutanugarn': { instagramHandle: 'mo_moriya' },
  'nagai-kana': { instagramHandle: 'kana._.0616' },
  'nana-suganuma': { instagramHandle: 'nana_suganuma_official' },
  'miyuu-yamashita': { instagramHandle: 'miyuu_yamashita' },
  'nasa-hataoka': { instagramHandle: 'nasahataoka' },
  'nelly-korda': { instagramHandle: 'nellykorda' },
  'nick-taylor': { instagramHandle: 'ntaylorgolf59', xHandle: 'ntaylorgolf59' },
  'nozomi-uetake': { instagramHandle: 'nozomi_uetake' },
  'patrick-cantlay': { instagramHandle: 'patrickcantlay' },
  'patrick-reed': { instagramHandle: 'preedgolf' },
  'patty-tavatanakit': { instagramHandle: 'pattytavatanakit' },
  'peter-malnati': { instagramHandle: 'petermalnati', xHandle: 'PeterMalnati' },
  'rikuya-hoshino': { instagramHandle: 'rikuya_golf' },
  'rio-takeda': { instagramHandle: 'rio_takeda' },
  'rose-zhang': { instagramHandle: 'rosezhang', xHandle: 'rosezhang' },
  'rory-mcilroy': { instagramHandle: 'rorymcilroy' },
  'ryo-hisatsune': { instagramHandle: 'ryo_hisatsune' },
  'ryo-ishikawa': { instagramHandle: 'ryo.ishikawa_official' },
  'sahith-theegala': { instagramHandle: 'srtheegala' },
  'satoshi-kodaira': { instagramHandle: 'satoshi_kodaira_official' },
  'sakura-koiwai': { instagramHandle: 'sakura_koiwai_official' },
  'sam-burns': { instagramHandle: 'samburns66' },
  'sayaka-takahashi': { instagramHandle: 'sayaka_takahashi8' },
  'scottie-scheffler': { instagramHandle: 'scottie.scheffler' },
  'serena-aoki': { instagramHandle: 'serenaaoki_official' },
  'sepp-straka': { instagramHandle: 'seppstraka', xHandle: 'seppstraka' },
  'shane-lowry': { instagramHandle: 'shanelowrygolf' },
  'shiho-kuwaki': { instagramHandle: 'shiho_kuwaki' },
  'shingo-katayama': { instagramHandle: 'shingokatayama45' },
  'shugo-imahira': { instagramHandle: 'shugo_imahira' },
  'sungjae-im': { instagramHandle: 'sungjaeim330' },
  'taiga-semikawa': { instagramHandle: 'taiga_semikawa' },
  'taichi-nabetani': { instagramHandle: 'taichi_nabetani' },
  'taisei-shimizu': { instagramHandle: 'taisei_shimizu' },
  'thomas-detry': { instagramHandle: 'tomdetry', xHandle: 'tomdetry' },
  'thorbjorn-olesen': { instagramHandle: 'thorbjornolesen', xHandle: 'Thorbjornolesen' },
  'tiger-woods': { instagramHandle: 'tigerwoods' },
  'tony-finau': { instagramHandle: 'tonyfinaugolf' },
  'tommy-fleetwood': { instagramHandle: 'tommyfleetwood_1' },
  'tom-kim': { instagramHandle: 'joohyungkim0621' },
  'tomoharu-otsuki': { instagramHandle: 'tomoharu_otsuki' },
  'tomohiro-ishizaka': { instagramHandle: 'tomohiro_ishizaka' },
  'toru-taniguchi': { instagramHandle: 'torutaniguchi' },
  'viktor-hovland': { instagramHandle: 'viktor_hovland' },
  'wyndham-clark': { instagramHandle: 'wyndhamclark' },
  'xander-schauffele': { instagramHandle: 'xanderschauffele' },
  'yuka-saso': { instagramHandle: 'yukasaso_official' },
  'yui-kawamoto': { instagramHandle: 'yui_kawamoto_official' },
  'yuna-nishimura': { instagramHandle: 'yunanishimura_official' },
  'yuri-yoshida': { instagramHandle: 'yuri_yoshida_official' },
};

export const getProfileSocialOverride = (slug: string): ProfileSocialOverride | undefined => profileSocialOverrides[slug];
