export interface ProfileSocialOverride {
  instagramHandle?: string;
  xHandle?: string;
}

export const profileSocialOverrides: Record<string, ProfileSocialOverride> = {
  'adam-scott': { instagramHandle: 'adamscottofficial' },
  'aguri-iwasaki': { instagramHandle: 'aguri_iwasaki' },
  'ayaka-furue': { instagramHandle: 'ayaka_furue27' },
  'brian-harman': { instagramHandle: 'harmanbrian' },
  'brooke-henderson': { instagramHandle: 'brookehendersongolf' },
  'chisato-iwai': { instagramHandle: 'chisato.iwai_101' },
  'collin-morikawa': { instagramHandle: 'collin_morikawa' },
  'charley-hull': { instagramHandle: 'charley.hull' },
  'jason-day': { instagramHandle: 'jdaygolf' },
  'jeeno-thitikul': { instagramHandle: 'jeenothitikul' },
  'jon-rahm': { instagramHandle: 'jonrahm' },
  'justin-thomas': { instagramHandle: 'justinthomas34' },
  'hideki-matsuyama': { instagramHandle: 'hideki.matsuyama_official' },
  'hideto-tanihara': { instagramHandle: 'hideto_tanihara' },
  'hinako-shibuno': { instagramHandle: 'pinacoooon' },
  'in-gee-chun': { instagramHandle: 'ingeechun_dumbo' },
  'justin-rose': { instagramHandle: 'justinprose99' },
  'kaito-onishi': { instagramHandle: 'kaito_onishi' },
  'keegan-bradley': { instagramHandle: 'keeganbradley1' },
  'keita-nakajima': { instagramHandle: 'keita.n_0624' },
  'kensei-hirata': { instagramHandle: 'k_e_n_s_e_i_1126' },
  'kotone-hori': { instagramHandle: 'kotone_hori' },
  'kumiko-kaneda': { instagramHandle: 'kinkumikinkumi' },
  'ludvig-aberg': { instagramHandle: 'ludvigaberg' },
  'lydia-ko': { instagramHandle: 'lydsko' },
  'mamiko-higa': { instagramHandle: 'mamiko_higa' },
  'mao-saigo': { instagramHandle: 'mao_saigo' },
  'matt-fitzpatrick': { instagramHandle: 'mattfitz94' },
  'min-woo-lee': { instagramHandle: 'minwoo27lee' },
  'minjee-lee': { instagramHandle: 'minjee27' },
  'miyuu-yamashita': { instagramHandle: 'miyuu_yamashita' },
  'nasa-hataoka': { instagramHandle: 'nasahataoka' },
  'nelly-korda': { instagramHandle: 'nellykorda' },
  'patrick-cantlay': { instagramHandle: 'patrickcantlay' },
  'patrick-reed': { instagramHandle: 'preedgolf' },
  'rikuya-hoshino': { instagramHandle: 'rikuya.hoshino_official' },
  'rio-takeda': { instagramHandle: 'rio_takeda_official' },
  'rory-mcilroy': { instagramHandle: 'rorymcilroy' },
  'ryo-hisatsune': { instagramHandle: 'ryo_hisatsune' },
  'ryo-ishikawa': { instagramHandle: 'ryo.ishikawa_official' },
  'sahith-theegala': { instagramHandle: 'srtheegala' },
  'sakura-koiwai': { instagramHandle: 'sakura_koiwai_official' },
  'sam-burns': { instagramHandle: 'samburns66' },
  'sayaka-takahashi': { instagramHandle: 'sayaka_takahashi8' },
  'scottie-scheffler': { instagramHandle: 'scottie.scheffler' },
  'serena-aoki': { instagramHandle: 'serenaaoki_official' },
  'shane-lowry': { instagramHandle: 'shanelowrygolf' },
  'sungjae-im': { instagramHandle: 'sungjae__im' },
  'tiger-woods': { instagramHandle: 'tigerwoods' },
  'tommy-fleetwood': { instagramHandle: 'tommyfleetwood_1' },
  'tomoharu-otsuki': { instagramHandle: 'tomoharu.otsuki' },
  'tomohiro-ishizaka': { instagramHandle: 'tomohiro.ishizaka' },
  'ayaka-watanabe': { instagramHandle: 'watanabeayaka_official' },
  'viktor-hovland': { instagramHandle: 'viktor_hovland' },
  'wyndham-clark': { instagramHandle: 'wyndhamclark' },
  'xander-schauffele': { instagramHandle: 'xanderschauffele' },
  'yui-kawamoto': { instagramHandle: 'kawamotoyui_official' },
  'yuka-saso': { instagramHandle: 'yukasaso_official' },
};

export const getProfileSocialOverride = (slug: string): ProfileSocialOverride | undefined => profileSocialOverrides[slug];
