export interface ProfileSocialOverride {
  instagramHandle?: string;
  xHandle?: string;
}

export const profileSocialOverrides: Record<string, ProfileSocialOverride> = {
  'aaron-rai': { instagramHandle: 'aaron.rai1' },
  'adam-scott': { instagramHandle: 'adamscottofficial' },
  'aguri-iwasaki': { instagramHandle: 'aguriiwasaki' },
  'ai-suzuki': { instagramHandle: 'suzuki_ai_official' },
  'akie-iwai': { instagramHandle: 'akie.iwai' },
  'alison-lee': { instagramHandle: 'thealisonlee', xHandle: 'alisonlee' },
  'allisen-corpuz': { instagramHandle: 'allysoncorpuz', xHandle: 'allisencorpuz' },
  'ally-ewing': { instagramHandle: 'a_mc10', xHandle: 'allyewing' },
  'amiyu-ozeki': { instagramHandle: 'z.amiyu616' },
  'amy-yang': { instagramHandle: 'amy_yang_golf' },
  'andrea-lee': { instagramHandle: 'andrealee', xHandle: 'andrea_lee54' },
  'angel-yin': { instagramHandle: 'angelyin', xHandle: 'angelyinlol' },
  'anna-nordqvist': { instagramHandle: 'a_nordqvist', xHandle: 'ANordqvist' },
  'aoki-serena': { instagramHandle: 'serenaaoki_official', xHandle: 'serenaaoki28' },
  'arimura-chie': { instagramHandle: 'chiearimura' },
  'ariya-jutanugarn': { instagramHandle: 'mayariya' },
  'ashleigh-buhai': { instagramHandle: 'ashbuhaigolf', xHandle: 'ashbuhai' },
  'asuka-kashiwabara': { instagramHandle: 'asuka_____official' },
  'ayaka-furue': { instagramHandle: 'ayaka_furue27' },
  'ayaka-watanabe': { instagramHandle: 'watanabeayaka_official' },
  'ayako-kimura': { instagramHandle: 'ayako___kimura' },
  'ayano-yasuda': { instagramHandle: 'yasuda.ayano' },
  'brian-harman': { instagramHandle: 'harmanbrian' },
  'brooke-henderson': { instagramHandle: 'brookehendersongolf' },
  'brooks-koepka': { instagramHandle: 'bkoepka', xHandle: 'BKoepka' },
  'cameron-smith': { instagramHandle: 'camsmithgolf' },
  'cameron-young': { instagramHandle: 'cameron_young' },
  'carlota-ciganda': { instagramHandle: 'carlotagolf', xHandle: 'carlotagolf' },
  'celine-boutier': { instagramHandle: 'celineboutier', xHandle: 'celineboutier' },
  'charley-hull': { instagramHandle: 'charley.hull' },
  'chisato-iwai': { instagramHandle: 'chisato.iwai_101' },
  'collin-morikawa': { instagramHandle: 'collin_morikawa' },
  'corey-conners': { instagramHandle: 'coreyconners', xHandle: 'coreconn' },
  'daijiro-izumida': { instagramHandle: 'dai26insta' },
  'danielle-kang': { instagramHandle: 'daniellekang', xHandle: 'daniellekang' },
  'eri-okayama': { instagramHandle: 'eri.okayama1996' },
  'erika-hara': { instagramHandle: 'warriorsmilerika_9' },
  'erika-kikuchi': { instagramHandle: 'erika_kikuchi_official' },
  'fukuda-mami': { instagramHandle: 'fukudamami32', xHandle: 'maami_maami32' },
  'gaby-lopez': { instagramHandle: 'gabylopezgolf', xHandle: 'GabyLopezGOLF' },
  'georgia-hall': { instagramHandle: 'georgiahall23', xHandle: 'georgiahall96' },
  'goto-miu': { instagramHandle: 'mg____0929' },
  'haeran-ryu': { instagramHandle: 'haeran_ryu' },
  'hannah-green': { instagramHandle: 'hannahgreengolf', xHandle: 'hannahgreengolf' },
  'haruka-amamoto': { instagramHandle: 'haruka.no.1' },
  'haruka-kawasaki': { instagramHandle: 'with_harugolfer_days' },
  'hideto-tanihara': { instagramHandle: 'hidetotanihara' },
  'higa-mamiko': { instagramHandle: 'mamiko_higa_official' },
  'hibiki-iriya': { instagramHandle: 'roihibiki' },
  'hideki-matsuyama': { instagramHandle: 'hideki.matsuyama_official' },
  'hinako-shibuno': { instagramHandle: 'pinacoooon' },
  'hyo-joo-kim': { instagramHandle: 'hyojookim' },
  'in-gee-chun': { instagramHandle: 'ingeechun_dumbo' },
  'inbee-park': { instagramHandle: 'inbeelievable' },
  'jason-day': { instagramHandle: 'jasondayofficial' },
  'jeeno-thitikul': { instagramHandle: 'jeeno.atthaya' },
  'jennifer-kupcho': { instagramHandle: 'jenniferkupcho', xHandle: 'jenniferkupcho' },
  'jin-young-ko': { instagramHandle: 'jinyoungko_official' },
  'jinichiro-kozuma': { instagramHandle: 'kozumajinichiro' },
  'joaquin-niemann': { instagramHandle: 'joaco_niemann' },
  'jon-rahm': { instagramHandle: 'jonrahm' },
  'jordan-spieth': { instagramHandle: 'jordanspieth' },
  'justin-rose': { instagramHandle: 'justinprose99' },
  'justin-thomas': { instagramHandle: 'justinthomas34' },
  'kaito-onishi': { instagramHandle: 'kaito_onishi' },
  'kanako-aoki': { instagramHandle: 'knk_aoki' },
  'kanazawa-shina': { instagramHandle: 'shina_kanazawa' },
  'kaneda-kumiko': { instagramHandle: 'kinkumiringo93', xHandle: 'kinkumiringo' },
  'kano-nakamura': { instagramHandle: 'kanonakamura_' },
  'karen-fujita': { instagramHandle: 'karenman_14' },
  'kasa-ritsuko': { instagramHandle: 'ryuritsuko' },
  'katsumasa-miyamoto': { instagramHandle: 'katsumasa_miyamoto' },
  'kawagishi-fumika': { instagramHandle: 'fumikakawagishi' },
  'kazuki-higa': { instagramHandle: 'kazuki_higa_official' },
  'keegan-bradley': { instagramHandle: 'keeganbradley1' },
  'keita-nakajima': { instagramHandle: 'keita.nkjm' },
  'kensei-hirata': { instagramHandle: 'kenseihirata' },
  'kido-ai': { instagramHandle: 'megumikidoofficial' },
  'kokona-sakurai': { instagramHandle: 'skr_coconut' },
  'kokone-yoshimoto': { instagramHandle: 'kokone_yoshimoto' },
  'konosuke-nakazato': { instagramHandle: 'konosukenakazato' },
  'kotaki-mion': { instagramHandle: 'ochobo36mio' },
  'kotoko-uchida': { instagramHandle: 'kotoko__uchida' },
  'kotone-hori': { instagramHandle: 'kotone_hori_official' },
  'kotono-kozuma': { instagramHandle: 'kotonokozuma' },
  'kozuma-kotono': { instagramHandle: 'kotonokozuma' },
  'kudo-haruka': { instagramHandle: 'harukakudo1118' },
  'kumiko-kaneda': { instagramHandle: 'kinkumiringo93', xHandle: 'kinkumiringo' },
  'lauren-coughlin': { instagramHandle: 'l_coughlin' },
  'leona-maguire': { instagramHandle: 'leonamaguire', xHandle: 'leona_maguire' },
  'lexi-thompson': { instagramHandle: 'lexi' },
  'lilia-vu': { instagramHandle: 'liliavu' },
  'linn-grant': { instagramHandle: 'linngrant' },
  'ludvig-aberg': { instagramHandle: 'luddeaberg' },
  'lydia-ko': { instagramHandle: 'lydsko' },
  'mamiko-higa': { instagramHandle: 'mamiko_higa_official' },
  'mao-saigo': { instagramHandle: 'maomao_golf' },
  'matsuda-rei': { instagramHandle: 'rei_matsuda.official' },
  'matt-fitzpatrick': { instagramHandle: 'mattfitz94' },
  'matt-mccarty': { instagramHandle: 'mattmccarty21', xHandle: 'mattmccarty21' },
  'max-homa': { instagramHandle: 'max.homa', xHandle: 'maxhoma23' },
  'maya-stark': { instagramHandle: 'majastark1' },
  'megan-khang': { instagramHandle: 'megan_khan', xHandle: 'megankhang1023' },
  'mikiya-akutsu': { instagramHandle: 'micky_ak317' },
  'mikashima-kana': { instagramHandle: 'kanayan0713_official' },
  'mikumu-horikawa': { instagramHandle: 'mikumu.h' },
  'min-woo-lee': { instagramHandle: 'minwoo27lee' },
  'minami-katsu': { instagramHandle: 'minami_katsu' },
  'minjee-lee': { instagramHandle: 'minjee27' },
  'mone-inami': { instagramHandle: 'mone173.golf' },
  'morita-haruka': { instagramHandle: 'moritaharuka5588' },
  'morita-rikako': { instagramHandle: '1_rikako' },
  'moriya-jutanugarn': { instagramHandle: 'mo_moriya' },
  'nagai-kana': { instagramHandle: 'kana._.0616' },
  'nana-suganuma': { instagramHandle: 'nanasuganuma_official' },
  'nanoko-hayashi': { instagramHandle: 'h._.nanoko24' },
  'miyuu-yamashita': { instagramHandle: 'miyuu_yamashita' },
  'nasa-hataoka': { instagramHandle: 'nasahataoka' },
  'nelly-korda': { instagramHandle: 'nellykorda' },
  'nick-taylor': { instagramHandle: 'nicktaylorgolf', xHandle: 'ntaylorgolf59' },
  'nozomi-uetake': { instagramHandle: 'nozoooomi_nonsuke' },
  'patrick-cantlay': { instagramHandle: 'patrickcantlay' },
  'patrick-reed': { instagramHandle: 'preedgolf' },
  'patty-tavatanakit': { instagramHandle: 'impattyt' },
  'peter-malnati': { instagramHandle: 'peter_malnati', xHandle: 'PeterMalnati' },
  'ren-yonezawa': { instagramHandle: 'yoneren_golf_no1' },
  'riki-kawamoto': { instagramHandle: 'rickygolf54_riki.kawamoto' },
  'rikuya-hoshino': { instagramHandle: 'hoshinorikuya' },
  'rio-takeda': { instagramHandle: 'rio_tkd402' },
  'rose-zhang': { instagramHandle: 'rosezhang', xHandle: 'rosezhang' },
  'rory-mcilroy': { instagramHandle: 'rorymcilroy' },
  'ryo-hisatsune': { instagramHandle: 'ryo1499golf' },
  'ryo-ishikawa': { instagramHandle: 'ryo.ishikawa_official' },
  'sahith-theegala': { instagramHandle: 'srtheegala' },
  'sakuma-akari': { instagramHandle: 's_golf1211' },
  'sam-burns': { instagramHandle: 'samburns66' },
  'sami-valimaki': { instagramHandle: 'samioskarii' },
  'satoshi-kodaira': { instagramHandle: 'satoshi_kodaira_official' },
  'sayaka-takahashi': { instagramHandle: 't_sayaka724' },
  'sakura-koiwai': { instagramHandle: 'sakura_koiwai_official' },
  'scottie-scheffler': { instagramHandle: 'scottie.scheffler' },
  'serena-aoki': { instagramHandle: 'serenaaoki_official' },
  'sepp-straka': { instagramHandle: 'seppstraka', xHandle: 'seppstraka' },
  'shane-lowry': { instagramHandle: 'shanelowrygolf' },
  'shiho-kuwaki': { instagramHandle: 'kuwashiho' },
  'shingo-katayama': { instagramHandle: 'shingo_katayama45' },
  'shota-akiyoshi': { instagramHandle: 'shota.akiyoshi' },
  'shugo-imahira': { instagramHandle: 'shugo_imahira05' },
  'shunya-takeyasu': { instagramHandle: 'shunyatakeyasu' },
  'sungjae-im': { instagramHandle: 'sungjaeim330' },
  'taiga-semikawa': { instagramHandle: 'taiga.1.11' },
  'taichi-nabetani': { instagramHandle: 'taichinabetani' },
  'taisei-shimizu': { instagramHandle: 'taiseishimizu' },
  'takamitsu-tokimatsu': { instagramHandle: 'genzo_tokimatsu' },
  'tatsunori-shogenji': { instagramHandle: 'genjigolf' },
  'thomas-detry': { instagramHandle: 'tomdetry', xHandle: 'tomdetry' },
  'thorbjorn-olesen': { instagramHandle: 'thorbjornolesen', xHandle: 'Thorbjornolesen' },
  'tiger-woods': { instagramHandle: 'tigerwoods' },
  'tom-kim': { instagramHandle: 'joohyungkim0621' },
  'tommy-fleetwood': { instagramHandle: 'tommyfleetwood_1' },
  'tomoharu-otsuki': { instagramHandle: 'tomoharu.otsuki' },
  'tomohiro-ishizaka': { instagramHandle: 'tomohiro.ishizaka' },
  'tony-finau': { instagramHandle: 'tonyfinaugolf' },
  'tsuruoka-karen': { instagramHandle: 'tsurukare' },
  'ueda-momoko': { instagramHandle: 'momoko3030' },
  'viktor-hovland': { instagramHandle: 'viktor_hovland' },
  'wakana-kamiya': { instagramHandle: 'wakana.kamiya' },
  'wyndham-clark': { instagramHandle: 'wyndhamclark' },
  'xander-schauffele': { instagramHandle: 'xanderschauffele' },
  'yoshimoto-hikaru': { instagramHandle: 'hikaru_yoshimoto_' },
  'yosuke-asaji': { instagramHandle: 'yo0524' },
  'yosuke-tsukada': { instagramHandle: 'boooochan24' },
  'yui-kawamoto': { instagramHandle: 'kawamotoyui_official' },
  'yuka-saso': { instagramHandle: 'yukasaso_official' },
  'yuki-inamori': { instagramHandle: 'inamori_yuki' },
  'yumeka-kobayashi': { instagramHandle: 'yumeka___036' },
  'yumeno-masada': { instagramHandle: 'yumeno__0728' },
  'yuna-nishimura': { instagramHandle: 'yunapan_02' },
  'yokomine-sakura': { instagramHandle: 'sakura_yokomine' },
  'yuri-yoshida': { instagramHandle: 'yuri_yoshida__' },
  'yuuka-yasuda': { instagramHandle: 'oo_______yuka', xHandle: 'y_2424_' },
  'yuta-ikeda': { instagramHandle: 'yutaikeda33_official' },
  'yuto-katsuragawa': { instagramHandle: 'yutokatsu' },
};

export const getProfileSocialOverride = (slug: string): ProfileSocialOverride | undefined => profileSocialOverrides[slug];
