-- Optional Golf ID explore seed data for development/staging.
-- Do not run this in production unless you intentionally want sample public profiles.
-- Run docs/sql/golf-profiles-mvp.sql first.

insert into public.golf_profiles (
  username,
  nickname,
  best_score,
  average_score,
  target_score,
  head_speed,
  golf_history,
  favorite_club,
  weak_club,
  current_issue,
  club_setting,
  visibility,
  diagnosis_result,
  is_public
)
select *
from (
  values
    (
      'goal-79-golfer',
      '80切り目標ゴルファー',
      82,
      90,
      79,
      42.0,
      '8年',
      '7I',
      '3W',
      'アイアンの縦距離をそろえて80切りを狙いたい。',
      '1W PING G425 LST' || E'\n' || '5W TaylorMade Qi10' || E'\n' || '5I-PW Yamaha inpres XV forged tour',
      '{"best_score":true,"target_score":true,"head_speed":true,"club_setting":true,"current_issue":true}'::jsonb,
      '{"diagnosisType":"80切り準備タイプ","nextAction":"150y以内の番手精度を優先して見直しましょう。"}'::jsonb,
      true
    ),
    (
      'break-100-weekend',
      '100切り週末ゴルファー',
      103,
      110,
      99,
      39.0,
      '3年',
      'UT',
      '1W',
      'ドライバーの右ミスと、長いアイアンのミスを減らしたい。',
      '1W TaylorMade SIM2 MAX' || E'\n' || '4U PING G430 Hybrid' || E'\n' || '7W Callaway ELYTE',
      '{"best_score":true,"target_score":true,"head_speed":true,"club_setting":true,"current_issue":true}'::jsonb,
      '{"diagnosisType":"100切り安定タイプ","nextAction":"5Iを無理に使わず、UTと7Wで距離の階段を作りましょう。"}'::jsonb,
      true
    ),
    (
      'driver-distance',
      'ドライバー飛距離重視',
      91,
      96,
      85,
      45.0,
      '6年',
      '1W',
      'ウェッジ',
      'ティーショットの飛距離を伸ばしつつ、左右の散らばりを減らしたい。',
      '1W Callaway ELYTE' || E'\n' || '3W TaylorMade Qi35' || E'\n' || 'Ball Titleist Pro V1x',
      '{"best_score":true,"target_score":true,"head_speed":true,"club_setting":true,"current_issue":true}'::jsonb,
      '{"diagnosisType":"飛距離アップタイプ","nextAction":"ロフトとシャフト重量を確認し、強く振っても左に行きにくい1Wへ寄せましょう。"}'::jsonb,
      true
    ),
    (
      'slice-fix',
      'スライス改善中',
      98,
      105,
      90,
      40.0,
      '4年',
      'PW',
      '1W',
      'スライスで右OBが出る。ドライバーを安心して振りたい。',
      '1W PING G430 MAX' || E'\n' || '5W Titleist TSR2' || E'\n' || '5U PING G430 Hybrid',
      '{"best_score":true,"target_score":true,"head_speed":true,"club_setting":true,"current_issue":true}'::jsonb,
      '{"diagnosisType":"スライス改善タイプ","nextAction":"つかまりとロフトを少し足して、右ミスを減らす構成にしましょう。"}'::jsonb,
      true
    ),
    (
      'iron-stability',
      'アイアン安定派',
      86,
      92,
      82,
      41.0,
      '10年',
      '8I',
      '4I',
      'アイアンの打点がバラつき、パーオン率が伸びない。',
      '1W Srixon ZXi' || E'\n' || '6I-PW Srixon ZX5 Mk II' || E'\n' || '50/56/60 Cleveland RTX',
      '{"best_score":true,"target_score":true,"head_speed":true,"club_setting":true,"current_issue":true}'::jsonb,
      '{"diagnosisType":"アイアン安定タイプ","nextAction":"6Iより上はUT化し、7I以下の距離精度に集中しましょう。"}'::jsonb,
      true
    ),
    (
      'putter-reset',
      'パター改善中',
      88,
      94,
      84,
      38.0,
      '7年',
      '52°',
      'PT',
      '3パットが多く、ショートパットを安心して打ちたい。',
      'PT Odyssey Ai-ONE' || E'\n' || 'Ball Bridgestone TOUR B X',
      '{"best_score":true,"target_score":true,"head_speed":false,"club_setting":true,"current_issue":true}'::jsonb,
      '{"diagnosisType":"パター改善タイプ","nextAction":"距離感の基準作りと、構えやすいヘッド形状の確認を優先しましょう。"}'::jsonb,
      true
    ),
    (
      'beginner-first-year',
      '初心者ゴルファー',
      118,
      125,
      110,
      35.0,
      '1年',
      '9I',
      '3W',
      'まずは大きなミスを減らしてラウンドを楽にしたい。',
      '1W Cobra AIR-X' || E'\n' || '7W PING G Le' || E'\n' || '7I-PW easy cavity irons',
      '{"best_score":true,"target_score":true,"head_speed":true,"club_setting":true,"current_issue":true}'::jsonb,
      '{"diagnosisType":"初心者やさしさ重視タイプ","nextAction":"長い番手を減らし、上がりやすいFW/UT中心にしましょう。"}'::jsonb,
      true
    ),
    (
      'competitive-amateur',
      '競技志向アマ',
      74,
      78,
      72,
      48.0,
      '15年',
      '1W',
      '58°',
      '強い球で狙えるが、ウェッジの距離感をさらに詰めたい。',
      '1W Titleist GT3' || E'\n' || '4I Titleist T200' || E'\n' || '5I-PW Titleist T100',
      '{"best_score":true,"target_score":true,"head_speed":true,"club_setting":true,"current_issue":true}'::jsonb,
      '{"diagnosisType":"競技志向タイプ","nextAction":"ウェッジのロフト間隔とキャリー基準を細かく管理しましょう。"}'::jsonb,
      true
    ),
    (
      'women-golfer-90',
      '女性ゴルファー',
      94,
      101,
      89,
      34.0,
      '5年',
      '7W',
      '5I',
      '180y前後を安定して打てるクラブを探したい。',
      '1W TaylorMade Qi35 MAX Lite' || E'\n' || '7W TaylorMade Qi35' || E'\n' || '5U PING G440 Hybrid',
      '{"best_score":true,"target_score":true,"head_speed":true,"club_setting":true,"current_issue":true}'::jsonb,
      '{"diagnosisType":"FW/UT活用タイプ","nextAction":"5Iを無理に使わず、7WとUTで高さを作りましょう。"}'::jsonb,
      true
    ),
    (
      'senior-golfer',
      'シニアゴルファー',
      89,
      96,
      85,
      36.0,
      '25年',
      'UT',
      'ロングアイアン',
      '飛距離が少し落ちてきたので、楽に上がる構成へ変えたい。',
      '1W XXIO 13' || E'\n' || '5W XXIO 13' || E'\n' || '6U PING G430 Hybrid',
      '{"best_score":true,"target_score":true,"head_speed":true,"club_setting":true,"current_issue":true}'::jsonb,
      '{"diagnosisType":"やさしさ再設計タイプ","nextAction":"軽量シャフトと高ロフトFW/UTで、無理なく距離をつなぎましょう。"}'::jsonb,
      true
    )
) as seed(
  username,
  nickname,
  best_score,
  average_score,
  target_score,
  head_speed,
  golf_history,
  favorite_club,
  weak_club,
  current_issue,
  club_setting,
  visibility,
  diagnosis_result,
  is_public
)
where not exists (
  select 1
  from public.golf_profiles existing
  where lower(existing.username) = lower(seed.username)
);
